- name: Configuring Mongodb Component
  hosts: Mongodb
  become: yes
  tasks:
  
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo 